services:
  db: 
    image: pgvector/pgvector:pg17 
    container_name: rag-forge
    restart: always
    environment: 
      POSTGRES_USER: ragforge
      POSTGRES_PASSWORD: ragforgedb
      POSTGRES_DB: ragforgedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: