[project]
name = "rag-forge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanishk0", email = "tanishkaggarwal245@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.3.6",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
rag-forge = "rag_forge:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
